name: Pylint

on:
  workflow_dispatch:
     inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test Run No'
        # Default value if no value is explicitly provided
        default: '1'
        # Input has to be provided for the workflow to run
        required: true
env:
  TEST_G: mkdir
  TEST_PART1: AAAA
  TEST_PART2: BBBB
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    
     
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create directory
      run: ${{env.TEST_G}} ${{env.TEST_PART1}}${{env.TEST_PART2}}
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: show files
      run: |
        ls
    - name: show filesgit
      run: |
        echo $(git ls-files '*.py')
    
    - name: Analysing the code with pylint
      run: |
        pylint service/*.py
        
